### ISSUE TITLE
how to help

### ISSUE THREAD

**Issue by TiloGit** [alexsanjoseph/duolingo-save-streak#1] opened 2019-03-28 16:01 UTC
Hi, great idea to run on Lambda, 

could you please expand your HowTo/readme a bit. 
I tried and end up with this error: (I added Environment variables a single username and pw) 

```
{
  "errorMessage": "name 'usernames' is not defined",
  "errorType": "NameError",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
    "  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
    "  File \"<frozen importlib._bootstrap>\", line 696, in _load\n",
    "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 28, in <module>\n    list(map(process_single_user, usernames, passwords))\n"
  ]
}
```

In general I did: 
Upload layer: (zip from https://github.com/alexsanjoseph/duolingo-save-streak/blob/master/Archive.zip)
 https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/layers

add the main_AWS.py to the Lambda function designer.

my CouldWatch Event is this cron job for every6hrs: 

> cron(0 2,8,14,20 * * ? *)

**Comment by TiloGit** [comment] 2019-03-29 01:00
got something working, 

I copy/paste a modified duolingo.py

```python 
"""Unofficial API for duolingo.com"""
import re
import json
import random

#import requests
from botocore.vendored import requests
#from werkzeug.datastructures import MultiDict
```

and used this as main code: (with env variables)
Handler for Lambda: **main_AWS.main** ; timeout 15sec
```python 
def main(a, b):
    import duolingo, os

    username = os.environ['usernames']
    password = os.environ['passwords']

    print("TestTiloHere")
    print("environment variable: " + os.environ['usernames'])
    print("loaded one: " + username)

    try:
        lingo = duolingo.Duolingo(username, password)
    except ValueError:
        raise Exception("Username Invalid")

#here the test/report stuff
    print("Trying to check get_languages for " + username)
    Mylanguages = lingo.get_languages()
    print(username + " get_languages for " + str(Mylanguages))
    print("Trying to check get_streak_info for " + username)
    streak_info = lingo.get_streak_info()
    print(username +"get_streak_info for " + str(streak_info))

#here the buy stuff
    print("Trying to Buy Streak Freeze for " + username)
    BuyStreak = lingo.buy_streak_freeze()
    print(username +" streak freeze for " + str(BuyStreak))

    try:
        print("Trying to Buy Double or nothing for " + username)
        lingo.buy_item('rupee_wager', 'en')
        print("Bought Double or nothing for " + username)
    except:
        print("Unable to buy double or nothing")
```

here the result of test: 

> START RequestId: ---cut---9b6d-4510-8c82----cut-- Version: $LATEST
> TestTiloHere
> environment variable: MyUserIDduo123
> loaded one: MyUserIDduo123
> Trying to check get_languages for MyUserIDduo123
> MyUserIDduo123 get_languages for ['Spanish']
> Trying to check get_streak_info for MyUserIDduo123
> MyUserIDduo123get_streak_info for {'daily_goal': 50, 'site_streak': 1087, 'streak_extended_today': True}
> Trying to Buy Streak Freeze for MyUserIDduo123
> MyUserIDduo123 streak freeze for False
> Trying to Buy Double or nothing for MyUserIDduo123
> Unable to buy double or nothing
> END RequestId: ---cut---9b6d-4510-8c82----cut--
> REPORT RequestId: ---cut---9b6d-4510-8c82----cut--	Duration: 3661.10 ms	Billed Duration: 3700 ms 	Memory Size: 128 MB	Max Memory Used: 33 MB

**Comment by alexsanjoseph** [comment] 2019-03-29 03:38
@TiloGit - Thanks! Wanted to do the readme some time, but missed it. Were you able to get it working correctly? 

Can I add this to the readme (with acknowledgements?)

**Comment by alexsanjoseph** [comment] 2019-03-29 03:39
Why did you have to modify the duolingo.py?

**Comment by alexsanjoseph** [comment] 2019-03-29 03:41
Oh yeah, you're right, I never fixed it after the latest Duolingo API update. Will update it, thanks

Update: Unable to replicate the issue, my AWS version (which works) runs the same code as local. Can you help me identify the problem? @TiloGit

**Comment by TiloGit** [comment] 2019-04-02 17:45
Hi, 

yes please use anything as you wish. 

I couldn't get your script to work (maybe due to the missing how to =)

I got it working with the above changes. 
change of "duolingo.py" to use native lambda requests
`from botocore.vendored import requests`
and comment out the werkzeug stuff as it seems not needed for the buy part (and werkzeug is not native to lambda
`#from werkzeug.datastructures import MultiDict`

Also changed your main code as the multi user/pw seems to cause trouble (I only have one user to process)

**Comment by alexsanjoseph** [comment] 2019-04-14 11:07
Bizzarely enough I'm not able to reproduce the issue - Closing this!

I'll hopefully get around to better documentation soon :(

**Closed as completed by alexsanjoseph** 2019-04-14 11:07 UTC
Labels: bug
